# Generated by Django 4.1.5 on 2023-02-12 16:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='stone_images',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
